app.name=Job Application (DEV MODE)
logging.level.cr.ac.una.job=INFO
spring.datasource.url=jdbc:mysql://localhost:3306/bolsa_empleo?useSSL=false&serverTimezone=America/Costa_Rica&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=root1234
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update